bebidas = [
    {"name": "Chardonnay", "intensity": "Suave", "flavor_profile": "Frutal", "drink_type": "Vino", "temperature": "Fría", "bubbles": False},
    {"name": "Cabernet Sauvignon", "intensity": "Fuerte", "flavor_profile": "Seco", "drink_type": "Vino", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Merlot", "intensity": "Intermedio", "flavor_profile": "Suave", "drink_type": "Vino", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Syrah", "intensity": "Fuerte", "flavor_profile": "Ahumado", "drink_type": "Vino", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Prosecco", "intensity": "Intermedio", "flavor_profile": "Frutal", "drink_type": "Vino", "temperature": "Fría", "bubbles": True},
    {"name": "Champagne", "intensity": "Intermedio", "flavor_profile": "Seco", "drink_type": "Vino", "temperature": "Fría", "bubbles": True},
    {"name": "Pinot Noir", "intensity": "Suave", "flavor_profile": "Terroso", "drink_type": "Vino", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Sauvignon Blanc", "intensity": "Suave", "flavor_profile": "Herbal", "drink_type": "Vino", "temperature": "Fría", "bubbles": False},
    {"name": "Zinfandel", "intensity": "Intermedio", "flavor_profile": "Frutal", "drink_type": "Vino", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Moscato", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Vino", "temperature": "Fría", "bubbles": False},
    {"name": "Tempranillo", "intensity": "Fuerte", "flavor_profile": "Terroso", "drink_type": "Vino", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Malbec", "intensity": "Intermedio", "flavor_profile": "Ahumado", "drink_type": "Vino", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Riesling", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Vino", "temperature": "Fría", "bubbles": False},
    {"name": "Gin Tonic", "intensity": "Intermedio", "flavor_profile": "Amargo", "drink_type": "Coctel", "temperature": "Fría", "bubbles": True},
    {"name": "Margarita", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False},
    {"name": "Piña Colada", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False},
    {"name": "Bloody Mary", "intensity": "Fuerte", "flavor_profile": "Picante", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False},
    {"name": "Martini", "intensity": "Intermedio", "flavor_profile": "Seco", "drink_type": "Coctel", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Negroni", "intensity": "Fuerte", "flavor_profile": "Amargo", "drink_type": "Coctel", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Caipirinha", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False},
    {"name": "Old Fashioned", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Mojito", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": True},
    {"name": "Tequila Sunrise", "intensity": "Intermedio", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False},
    {"name": "Cosmopolitan", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False},
    {"name": "Whisky Escocés", "intensity": "Fuerte", "flavor_profile": "Ahumado", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Whisky Bourbon", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Vodka", "intensity": "Intermedio", "flavor_profile": "Neutral", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Gin", "intensity": "Intermedio", "flavor_profile": "Herbal", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Tequila Blanco", "intensity": "Fuerte", "flavor_profile": "Ahumado", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Tequila Reposado", "intensity": "Fuerte", "flavor_profile": "Ahumado", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Brandy", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Cognac", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Absenta", "intensity": "Muy fuerte", "flavor_profile": "Herbal", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Campari", "intensity": "Intermedio", "flavor_profile": "Amargo", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Amaretto", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Baileys", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Licor cremoso", "temperature": "Fría", "bubbles": False},
    {"name": "Kahlúa", "intensity": "Intermedio", "flavor_profile": "Dulce", "drink_type": "Licor cremoso", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Rum Blanco", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Rum Oscuro", "intensity": "Fuerte", "flavor_profile": "Ahumado", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Limoncello", "intensity": "Suave", "flavor_profile": "Dulce", "drink_type": "Licor puro", "temperature": "Fría", "bubbles": False},
    {"name": "Sake", "intensity": "Suave", "flavor_profile": "Seco", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Cerveza Lager", "intensity": "Suave", "flavor_profile": "Amargo", "drink_type": "Cerveza", "temperature": "Fría", "bubbles": True},
    {"name": "Cerveza IPA", "intensity": "Fuerte", "flavor_profile": "Amargo", "drink_type": "Cerveza", "temperature": "Fría", "bubbles": True},
    {"name": "Cerveza Stout", "intensity": "Fuerte", "flavor_profile": "Ahumado", "drink_type": "Cerveza", "temperature": "Fría", "bubbles": True},
    {"name": "Cerveza Pilsner", "intensity": "Intermedio", "flavor_profile": "Amargo", "drink_type": "Cerveza", "temperature": "Fría", "bubbles": True},
    {"name": "Vermouth", "intensity": "Intermedio", "flavor_profile": "Herbal", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Aguardiente", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Pastis", "intensity": "Intermedio", "flavor_profile": "Herbal", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Mezcal", "intensity": "Muy fuerte", "flavor_profile": "Ahumado", "drink_type": "Licor puro", "temperature": "Temperatura ambiente", "bubbles": False},
    {"name": "Caipiroska", "intensity": "Intermedio", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False},
    {"name": "Pisco Sour", "intensity": "Fuerte", "flavor_profile": "Dulce", "drink_type": "Coctel", "temperature": "Fría", "bubbles": False}
]
